apiVersion: v1
kind: Service
metadata:
  name: ltc-compiler
  namespace: chibitronics
spec:
  selector:
    k8s-app: ltc-compiler
  ports:
  - name: fastcgi
    port: 9000
    protocol: UDP
  - name: fastcgi-tcp
    port: 9000
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ltc-compiler
  namespace: chibitronics
  labels:
    version: "1.9"
spec:
  replicas: 1
  selector:
    version: "1.9"
  template:
    metadata:
      labels:
        version: "1.9"
    spec:
      containers:
      - name: ltc-compiler
        image: xobs/ltc-compiler:1.9
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 9000
          name: fastcgi
          protocol: TCP
        - containerPort: 9000
          name: fastcgi-udp
          protocol: UDP
