apiVersion: v1
kind: Service
metadata:
  name: ltc-ux
  namespace: chibitronics
  labels:
    k8s-app: ltc-ux
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "ltc-ux"
spec:
  selector:
    k8s-app: ltc-ux
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - 188.166.182.54
    

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: ltc-ux
  namespace: default
  labels:
    k8s-app: ltc-ux
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 25
  selector:
    k8s-app: ltc-ux
    version: v1
  template:
    metadata:
      labels:
        k8s-app: ltc-ux
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: ltc-ux
        image: xobs/ltc-ux:1.5
        resources:
          limits:
            cpu: 25m
            memory: 32Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5

