#cloud-config

coreos:
  units:
    - name: "ltc-network.service"
      command: start
      content: |
        [Unit]
        Description=LtC network creation
        After=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        TimeoutStartSec=0
        ExecStart=-/usr/bin/docker network create ltc-network
        ExecStop=/usr/bin/docker network rm ltc-network
    - name: "ltc-ux.service"
      command: start
      content: |
        [Unit]
        Description=LtC web page
        After=docker.service ltc-network.service
        Requires=ltc-network.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill ltc-ux
        ExecStartPre=-/usr/bin/docker rm ltc-ux
        ExecStartPre=/usr/bin/docker pull xobs/ltc-ux:1.5
        ExecStart=/usr/bin/docker run --net=ltc-network --name ltc-ux xobs/ltc-ux:1.5
        ExecStop=/usr/bin/docker stop ltc-ux
    - name: "ltc-compiler.service"
      command: start
      content: |
        [Unit]
        Description=LtC backend compiler
        After=docker.service ltc-network.service
        Requires=ltc-network.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill ltc-compiler
        ExecStartPre=-/usr/bin/docker rm ltc-compiler
        ExecStartPre=/usr/bin/docker pull xobs/ltc-compiler:1.10
        ExecStart=/usr/bin/docker run --net=ltc-network --name ltc-compiler xobs/ltc-compiler:1.10
        ExecStop=/usr/bin/docker stop ltc-compiler
    - name: "ltc-compiler-frontend.service"
      command: start
      content: |
        [Unit]
        Description=LtC frontend for backend compiler
        After=docker.service ltc-compiler.service ltc-network.service
        Requires=ltc-compiler.service ltc-network.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill ltc-compiler-frontend
        ExecStartPre=-/usr/bin/docker rm ltc-compiler-frontend
        ExecStartPre=/usr/bin/docker pull xobs/ltc-compiler-frontend:1.6
        ExecStart=/usr/bin/docker run --net=ltc-network --name ltc-compiler-frontend xobs/ltc-compiler-frontend:1.6
        ExecStop=/usr/bin/docker stop ltc-compiler-frontend
    - name: "ltc-frontend.service"
      command: start
      content: |
        [Unit]
        Description=LtC frontend for the entire service
        After=docker.service ltc-compiler-frontend.service ltc-ux.service ltc-network.service
        Requires=ltc-compiler-frontend.service ltc-ux.service ltc-network.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill ltc-frontend
        ExecStartPre=-/usr/bin/docker rm ltc-frontend
        ExecStartPre=/usr/bin/docker pull xobs/ltc-frontend:1.1
        ExecStart=/usr/bin/docker run --net=ltc-network --name ltc-frontend -p 80:80 xobs/ltc-frontend:1.1
        ExecStop=/usr/bin/docker stop ltc-frontend
    - name: "extraswap.service"
      command: start
      content: |
        [Unit]
        Description=Make and turn on swap

        [Service]
        Type=oneshot
        ExecStartPre=-/usr/bin/fallocate -l 4096m /swapfile
        ExecStartPre=-/usr/bin/chmod 0600 /swapfile
        ExecStartPre=-/usr/bin/chattr +C /swapfile
        ExecStartPre=-/usr/sbin/mkswap /swapfile
        ExecStart=/usr/sbin/swapon /swapfile
        RemainAfterExit=true
        ExecStop=/usr/sbin/swapoff /swapfile

        [Install]
        WantedBy=multi-user.target
