#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  etcd2:
    #initial cluster configuration
    initial-advertise-peer-urls: https://$public_ipv4:2380
    listen-peer-urls: https://$public_ipv4:2380
    listen-client-urls: https://$public_ipv4:2379
    advertise-client-urls: https://$public_ipv4:2379
    initial-advertise-client-urls: https://$public_ipv4:2379
    initial-cluster-state: new
    #security
    trusted-ca-file: /home/core/ca.pem
    cert-file: /home/core/etcd.pem
    key-file: /home/core/etcd-key.pem
    client-cert-auth: 1
    peer-trusted-ca-file: /home/core/ca.pem
    peer-cert-file: /home/core/etcd.pem
    peer-key-file: /home/core/etcd-key.pem
    peer-client-cert-auth: 1
    #tuning see https://github.com/coreos/etcd/blob/master/Documentation/tuning.md
    heartbeat-interval: 100
    election-timeout: 2500
  fleet:
    public-ip: $public_ipv4   # used for fleetctl ssh command
    etcd-endpoints: https://$public_ipv4:2379
  locksmith:
    endpoint: https://$public_ipv4:2379
    etcd-cafile: /home/core/ca.pem
    etcd-certfile: /home/core/client.pem
    etcd-keyfile: /home/core/client-key.pem
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
write_files:
  - path: /run/systemd/system/fleet.service.d/30-certificates.conf
    permissions: 0644
    content: |
      [Service]
      # client auth certs
      Environment=ETCD_CAFILE=/home/core/ca.pem
      Environment=ETCD_CERTFILE=/home/core/etcd.pem
      Environment=ETCD_KEYFILE=/home/core/etcd-key.pem
  - path: "/etc/flannel/options.env"
    permissions: "0755"
    content: |
        FLANNELD_IFACE=$public_ipv4
        FLANNELD_ETCD_ENDPOINTS=https://$public_ipv4:2379
        FLANNELD_ETCD_CAFILE=/etc/ssl/etcd/ca.pem
        FLANNELD_ETCD_CERTFILE=/etc/ssl/etcd/client.pem
        FLANNELD_ETCD_KEYFILE=/etc/ssl/etcd/client-key.pem
  - path: "/etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf"
    permissions: "0755"
    content: |
        [Service]
        ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
  - path: "/etc/systemd/system/docker.service.d/40-flannel.conf"
    permissions: "0755"
    content: |
        [Unit]
        Requires=flanneld.service
        After=flanneld.service
