apiVersion: v1
kind: Service
metadata:
  name: ltc-compiler-frontend
  namespace: chibitronics
spec:
  selector:
    k8s-app: ltc-compiler-frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    externalIPs:
    - 188.166.182.54
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ltc-compiler-frontend
  namespace: chibitronics
  labels:
    version: "1.6"
spec:
  replicas: 1
  selector:
    version: "1.6"
  template:
    metadata:
      labels:
        version: "1.6"
    spec:
      containers:
      - name: ltc-compiler-frontend
        image: xobs/ltc-compiler-frontend:1.6
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
